//! Process-major: each session drags the model past memory in turn.
//!
//! Invariant: a session is served from the start of a token to its end
//! without interruption, then the next live session is, round-robin.
//! Design: docs/notes/mlos-sched.md.

use crate::{Schedule, Waiting};

/// The baseline: one session's whole token, then the next session's.
/// What `mlos-workload` generated by hand before a scheduler existed, and
/// what G4 was measured on.
#[derive(Clone, Copy, Debug, Default)]
pub struct ProcessMajor {
    current: usize,
    /// Whether `current` has been served since it was chosen; at a token
    /// boundary that is the difference between starting and finishing.
    started: bool,
}

impl Schedule for ProcessMajor {
    fn pick(&mut self, waiting: &dyn Waiting) -> Option<usize> {
        let count = waiting.sessions();
        if let Some(at) = waiting.at(self.current)
            && (at.index != 0 || !self.started)
        {
            self.started = true;
            return Some(self.current);
        }
        // The current session finished a token, or everything: rotate to
        // the next session with anything left.
        let next = (1..=count)
            .map(|step| (self.current + step) % count.max(1))
            .find(|&s| waiting.at(s).is_some())?;
        self.current = next;
        self.started = true;
        Some(next)
    }
}
