[package]
name        = "mlos-kernel"
version     = "0.0.1"
description = "The MLOS microkernel."
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true

[[bin]]
name = "mlos-kernel"
path = "src/main.rs"
test = false          # no test harness exists on a bare target
bench = false

[lints]
workspace = true

[target.'cfg(target_arch = "aarch64")'.dependencies]
mlos-device      = { path = "../mlos-device",      version = "0.0.1" }
mlos-gic-aarch64 = { path = "../mlos-gic-aarch64", version = "0.0.1" }
mlos-hal         = { path = "../mlos-hal",         version = "0.0.1" }
mlos-hal-aarch64 = { path = "../mlos-hal-aarch64", version = "0.0.1" }
mlos-machine     = { path = "../mlos-machine",     version = "0.0.1" }
mlos-mmu-aarch64 = { path = "../mlos-mmu-aarch64", version = "0.0.1" }
mlos-console     = { path = "../mlos-console",     version = "0.0.1" }
mlos-virtio      = { path = "../mlos-virtio",      version = "0.0.1" }
mlsh             = { path = "../mlsh",             version = "0.0.1" }
mlos-trap-aarch64 = { path = "../mlos-trap-aarch64", version = "0.0.1" }
