#include"b.c"//+-*%&|<>=~ .! @? #_ ^,
_Z(m6,i(n/4,Ez[4]={};EX=x;h(m,i(4,zi+=a[h]*X[i])X+=n)i(4,R_=zi)x+=4)i(n%4,e6 e={};EX=x++;h(m,e+=a[h]**X;X+=n)R_=e),im,in,e6*R,e2*a,e6*x)F(mv,R(tx,ma,e2*R=rV;i(ma,R_=EE(a2+i*nx,x))))
F(vm,ik=kx;R(tx,k,m6(mx,n4(k),rV,aV,xV)))F(mm,ik=kx;M(ma,k,i(ma,m6(mx,n4(k),r2+k*i,a2+mx*i,xV))))F(at,Qn(ka!=mn)_a(_x(ma|mx?(ma?mx?mm:mv:vm)(a,mx?x:P0(x)):te(EE(aV,x)))))
_F(S,Qn(ma!=mx|na!=nx)_a(_x(R(tx,kx,VR=rV;in=nr/16;i(n/4,Ez[4]={};EA=aV+4*i;EX=xV+4*i;i(mx,i(4,zi+=AZ*X_)A+=n-4;X+=n-4)i(4,R_=(V)zi))))))
G(VV,Qn(ka!=mn)_x(a)) //Qz(i&2!=i)it=ma;if(t){Uu=a;a=x;x=u;}ik=kx;_a(_x(M(mx,k,h(mx,VR=r2+h*k;VX=x2+h*k;$(t,EA=a2;$(i,J(4*k,R_=AZ*Ex))J(4*k,R_=AZ+Ex))$(i,J(4*k,R_=ae[h]*Ex))J(4*k,R_=ae[h]+Ex))))))
g(T,ax?4>i?t(i,ix):te(ex):t_(--i>tx?T(i,x):x))f(T4,4>tx?T(4,x):x)G(E4,ax?_v(E4(i,a,v(x))):eE(i,a?T4(a):a,P0(T4(x))))G(Q4,P(a,Qr(aa)(ma&&mx?S:at)(T4(a),x))_x(te(se(x)/nx)))
#define A(G,I,E) 4>i?V(4>tx?$3(i,I+Ix,I-Ix,(I)*Ix):(i6)$4(i,E+Ex,E-Ex,(E)*Ex,(E)/Ex)):6>i?V(3>tx?MG(G,*X):MI(I,*X)):3>tx?_V(1,U,bg($3(i-6,G<*X,G>*X,G==*X))):_V(1,i1,bi($3(i-6,I<(i6)*X,I>(i6)*X,I==(i6)*X)))
G(av,A(ga-z0,ia-z2,ea-ze))_U(Av,A(AZ,(i6)AZ,(e6)AZ),ii,VA,Ux)G(vv,_a(Av(i,a0,x)))g(pe,P(1==tx,pB(i,x))Ua=i?*xU:0;Uc=b(1<<bx);x=i--?Av(i^2>i-6,x0-(1<<bx-3),x):_x(ln(-1,nx,x));*xU=c&a|~c&*xU;x)
G(a9,P(3<tx,_v(av(i,a,v(x))))ij=ia;6>i?t(tx,$6(i,j+ix,j-ix,j*ix,0,l(j,ix),m(j,ix))):tb($3(i-6,j<ix,j>ix,j==ix)))f(y,4>tx?ti(-ix):te(-ex))
G(Z,P(!tx,Q(nx,Z(i,a,a_(j,x))))it=m(3>i?3:4>i?4:0,m(ta,tx));a=t>ta?T(t,a):a;x=t>tx?T(t,x):x;aa<ax?av(i-(1==i)^2>i-6,1==i?y(x):x,a):(aa?ax?a9:av:!ma^!mx?VV:vv)(i,a,x))
_g(z,!tx?Q(nx,z(i,a_(j,x))):$5(i,ti(ax?tx:_x(tx)),Z(1,ti(0),x),Z(2,r_(x),x),E4(3,0,x),10>i?tx?tb(!jx):V(~X_):ax?ti(ex):_t(x)))
G(MD,P(!i--|3<m(ta,tx),Z(2,i?a:te(1/ea),x))in=a;P(ax,ti(i?ix%n:ix/n))Qn(n-1>>16)im=(n+65535)/n;i?V(m*Ix>>16):V(i6 a=Ix;a-n*(m*a>>16)))G(P4,!a&3>i?o3(i,x):Q4(i,a,T4(x)))
F(A_,P(ma,M(nx,ka,ik=ka<<ba-3;i(nx,ds(k,r0+k*i,a0+k*x2[i]))))i2*X=x2;$4(ta,H(0,U,r_(aU[X_])),0,H(2,i0,a0[X_]),r(uz(x),i(nx,r2[i]=a2[X_]))))f(_n,ti(ax?1:_x(mn)))
_F(_A,Qr(ma)Qz(100<nx)Qt(ta!=tx|1<ta-2)H(3,i2,iz(3>tx?x0[j]:x2[j],a)))G(AA,it=i?ta:3;aa?MD(i,a,x):4==tx&!ax?at(a,x):_a(ax?i?ti(iz(x,a)):a_(x,a):(i?_A:A_)(a,t>tx?T(t,x):x)))
G(NN,Qr(!aa)in=a;P(ax,nz(n,x))im=mn;n>m?tx?0:Q(n,r_(xU[j%nx])):n>>31^i?(n+=!i*m,_x(ln(n,m-n,x))):x-(i?-n:m-n))F(C_,Qr(!aa|ax|mx)Qt(!tx)mz(ia>>31?nx/-ia:ia,x))
g(po,P(!i--,a_(nx-1,x))P(17==i,Qz(!tx)mz(0,x))P(2==i,Qt(3!=tx)_x(t(tx,pi(x))))Qz(!!i&1<i-4)o3(i?i-4:2,x))g(ps,Qz(!i--)Qz(mx)P(2>tx,sB(i,x))Qz(!!i&1<i-4)s3(i?i-4:2,x))g(io,0)g(is,0)
ZU e1(ii,U);f(s,!tx|mx?e1(11,x):_x(mz(2>nx?0:*x2,nz(pi(x),te(1)))))f(n_,ax?nz(x,0):4==tx?x:s(x))
Zf(f,ff,rr,o_,_o,fq,0,q0,n_,_v,uq,_n,0,sq,v,q0)_i(q,4>i|9==i|15==i)_g(e1,Q(mn,Ua=a_(j,x);q(i)?z(i,a):f[i-4](a)))Zg(g,ie,pe,io,po,is,ps)G(O3,QR Qz(!aa)!i&9>a-10?e1(a,x):g[2*i|pa](a,x))
G_(k,k_();!i--?a?(U)a0:x?r_(x):W:19>i?a?10>i?Z(i,a,x):16>i?(14>i?AA:NN)(1&i,a,x):$3(i-16,C_,_C,Q0)(a,x):q(i)?z(i,x):f[i-4](x):25>i?P4(i-19,a,x):28>i?E4(i-25,a,x):O3(i-28,a,x))
