[package]
name        = "mlos-machine"
version     = "0.0.1"
description = "The machine, as the device tree describes it: memory, CPUs, console."
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true

[dependencies]
mlos-fdt = { path = "../mlos-fdt", version = "0.0.1" }
mlos-hal = { path = "../mlos-hal", version = "0.0.1" }

[lints]
workspace = true
