[package]
name        = "mlos-virtio-blk"
version     = "0.0.1"
description = "A virtio block device: read sectors over a virtqueue."
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true

[dependencies]
mlos-abi    = { path = "../mlos-abi",    version = "0.0.1" }
mlos-virtio = { path = "../mlos-virtio", version = "0.0.1" }

[lints]
workspace = true
