[package]
name        = "mlos-image-map"
version     = "0.0.1"
description = "MLOS's built artifacts as a system-layout document."
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true

[dependencies]
mlos-abi        = { path = "../mlos-abi",        version = "0.0.1" }
mlos-elf        = { path = "../mlos-elf",        version = "0.0.1" }
mlos-layout     = { path = "../mlos-layout",     version = "0.0.1" }
mlos-objman     = { path = "../mlos-objman",     version = "0.0.1" }
mlos-objtab     = { path = "../mlos-objtab",     version = "0.0.1" }
mlos-lab        = { path = "../mlos-lab",        version = "0.0.1" }
mlos-synth      = { path = "../mlos-synth",      version = "0.0.1" }
mlos-virtio-blk = { path = "../mlos-virtio-blk", version = "0.0.1" }

[lints]
workspace = true
